// Generated by gencpp from file duckietown_msgs/ChangePatternRequest.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_CHANGEPATTERNREQUEST_H
#define DUCKIETOWN_MSGS_MESSAGE_CHANGEPATTERNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace duckietown_msgs
{
template <class ContainerAllocator>
struct ChangePatternRequest_
{
  typedef ChangePatternRequest_<ContainerAllocator> Type;

  ChangePatternRequest_()
    : pattern_name()  {
    }
  ChangePatternRequest_(const ContainerAllocator& _alloc)
    : pattern_name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _pattern_name_type;
  _pattern_name_type pattern_name;





  typedef boost::shared_ptr< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChangePatternRequest_

typedef ::duckietown_msgs::ChangePatternRequest_<std::allocator<void> > ChangePatternRequest;

typedef boost::shared_ptr< ::duckietown_msgs::ChangePatternRequest > ChangePatternRequestPtr;
typedef boost::shared_ptr< ::duckietown_msgs::ChangePatternRequest const> ChangePatternRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'duckietown_msgs': ['/duckietown/catkin_ws/src/dt-ros-commons/packages/duckietown_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "678f2d65b1bda577ab0910fd9c7414ba";
  }

  static const char* value(const ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x678f2d65b1bda577ULL;
  static const uint64_t static_value2 = 0xab0910fd9c7414baULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/ChangePatternRequest";
  }

  static const char* value(const ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String pattern_name\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pattern_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangePatternRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::ChangePatternRequest_<ContainerAllocator>& v)
  {
    s << indent << "pattern_name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.pattern_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_CHANGEPATTERNREQUEST_H
