// Generated by gencpp from file duckietown_msgs/LFstatusResponse.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_LFSTATUSRESPONSE_H
#define DUCKIETOWN_MSGS_MESSAGE_LFSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duckietown_msgs
{
template <class ContainerAllocator>
struct LFstatusResponse_
{
  typedef LFstatusResponse_<ContainerAllocator> Type;

  LFstatusResponse_()
    : voltage(0)  {
    }
  LFstatusResponse_(const ContainerAllocator& _alloc)
    : voltage(0)  {
  (void)_alloc;
    }



   typedef uint16_t _voltage_type;
  _voltage_type voltage;





  typedef boost::shared_ptr< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LFstatusResponse_

typedef ::duckietown_msgs::LFstatusResponse_<std::allocator<void> > LFstatusResponse;

typedef boost::shared_ptr< ::duckietown_msgs::LFstatusResponse > LFstatusResponsePtr;
typedef boost::shared_ptr< ::duckietown_msgs::LFstatusResponse const> LFstatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'duckietown_msgs': ['/duckietown/catkin_ws/src/dt-ros-commons/packages/duckietown_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ae362a2353c0f79b3f4102dac1ca3d0";
  }

  static const char* value(const ::duckietown_msgs::LFstatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ae362a2353c0f79ULL;
  static const uint64_t static_value2 = 0xb3f4102dac1ca3d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/LFstatusResponse";
  }

  static const char* value(const ::duckietown_msgs::LFstatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 voltage\n"
"\n"
"\n"
;
  }

  static const char* value(const ::duckietown_msgs::LFstatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LFstatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::LFstatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::LFstatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "voltage: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.voltage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_LFSTATUSRESPONSE_H
