// Generated by gencpp from file duckietown_msgs/SetCustomLEDPatternRequest.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_SETCUSTOMLEDPATTERNREQUEST_H
#define DUCKIETOWN_MSGS_MESSAGE_SETCUSTOMLEDPATTERNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <duckietown_msgs/LEDPattern.h>

namespace duckietown_msgs
{
template <class ContainerAllocator>
struct SetCustomLEDPatternRequest_
{
  typedef SetCustomLEDPatternRequest_<ContainerAllocator> Type;

  SetCustomLEDPatternRequest_()
    : pattern()  {
    }
  SetCustomLEDPatternRequest_(const ContainerAllocator& _alloc)
    : pattern(_alloc)  {
  (void)_alloc;
    }



   typedef  ::duckietown_msgs::LEDPattern_<ContainerAllocator>  _pattern_type;
  _pattern_type pattern;





  typedef boost::shared_ptr< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCustomLEDPatternRequest_

typedef ::duckietown_msgs::SetCustomLEDPatternRequest_<std::allocator<void> > SetCustomLEDPatternRequest;

typedef boost::shared_ptr< ::duckietown_msgs::SetCustomLEDPatternRequest > SetCustomLEDPatternRequestPtr;
typedef boost::shared_ptr< ::duckietown_msgs::SetCustomLEDPatternRequest const> SetCustomLEDPatternRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'duckietown_msgs': ['/duckietown/catkin_ws/src/dt-ros-commons/packages/duckietown_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df549e3242a29ae8542797d8cadb0afe";
  }

  static const char* value(const ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf549e3242a29ae8ULL;
  static const uint64_t static_value2 = 0x542797d8cadb0afeULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/SetCustomLEDPatternRequest";
  }

  static const char* value(const ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/LEDPattern pattern\n"
"\n"
"================================================================================\n"
"MSG: duckietown_msgs/LEDPattern\n"
"Header header\n"
"string[]  color_list\n"
"int8[]    color_mask\n"
"float32   frequency\n"
"int8[]    frequency_mask\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pattern);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCustomLEDPatternRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::SetCustomLEDPatternRequest_<ContainerAllocator>& v)
  {
    s << indent << "pattern: ";
    s << std::endl;
    Printer< ::duckietown_msgs::LEDPattern_<ContainerAllocator> >::stream(s, indent + "  ", v.pattern);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_SETCUSTOMLEDPATTERNREQUEST_H
